# Generated by Django 5.0.7 on 2024-07-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_category_description_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
